version: 2
jobs:
  build:
    filters:
      branches:
        only:
          - test
    docker:
      - image: circleci/python:3.6.5
    steps:
      - checkout
      - run:
          name: Install packages
          command: |
            sudo apt update
            sudo apt install openjdk-8-jdk
            sudo pip install awscli
      - run:
          name: Build WAR
          command: |
            echo "Current directory ->"
            pwd
            echo "list"
            ls -al
            cd csye-6225-aws-lambda
            echo "Current directory ->"
            pwd
            echo "list"
            ls
            ./mvnw clean package
            echo "Current directory ->"
            pwd
            echo "list"
            ls -la
            cd target
            echo "Current directory ->"
            pwd
            echo "listing all elements"
            ls -la
      # - run:
      #     name: Build Deployment Artifact
      #     command: |
      #       echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
      #       pwd
      #       ls -al
      #       mkdir -p codedeploy_artifact
      #       zip -r csye6225-webapp-${CIRCLE_BUILD_NUM}.zip webapp/librarymanagementsystem/target/librarymanagementsystem-0.0.1-SNAPSHOT.war infrastructure/aws/codedeploy/*.sh appspec.yml
      #       ls -al
      #       mv csye6225-webapp-${CIRCLE_BUILD_NUM}.zip codedeploy_artifact/
      #       ls -al
      #       pwd
      #       cd codedeploy_artifact
      #       ls -al
      #       pwd
      #       cd ..
      #       pwd
      #       ls -al
      - run:
          name: Upload Artifact to S3
          command: aws s3 cp ./csye-6225-aws-lambda/target/aws-lambda-0.0.1.zip s3://${S3_BUCKET_NAME}/aws-lambda-0.0.1-${CIRCLE_BUILD_NUM}.zip
      - run:
          name: Deploy artifact to ec2 instance
          command: |
            aws deploy create-deployment \
            --application-name csye6225-Lambda-function \
            --deployment-group-name csye6225-lambda-deployment \
            --s3-location bucket=${S3_BUCKET_NAME},bundleType=JSON|YAML,key=aws-lambda-0.0.1-${CIRCLE_BUILD_NUM}.zip \
            --region ${AWS_REGION}
